project:
  type: website
  resources:
    - "posts/**/*.mp4"

website:
  title: "Fai's Notes"
  open-graph: true
  repo-url: https:/github.com/faithefairy/fai-notes
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - href: posts/fluid-mechanics
        text: Fluid Mechanics
      - href: posts/nanoparticle-synthesis
        text: Nanoparticle Synthesis
      - href: posts/reactor-design
        text: Reactor Design
      - about.qmd
    right:
      - icon: envelope
        href: "mailto:me@faithefairy.com"
      - icon: github
        href: "https://github.com/faithefairy"

  page-footer:
    center: "Fai &copy; <script>document.write(new Date().getFullYear())</script>"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    html-math-method: katex
    respect-user-color-scheme: true
    code-fold: true
    code-tools:
      toggle: false
      source: repo
csl: assets/acs-nano.csl

